### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [josePhoenix/hershey#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert Persian fonts to Hershey fonts?

**Comment by josePhoenix** [comment]
The "Hershey" fonts are a specific data set with its own quirky [format](http://paulbourke.net/dataformats/hershey/). There isn't an easy conversion from other font types, since they usually define filled shapes and the Hershey fonts are strictly outlines for use with [plotters](https://en.wikipedia.org/wiki/Plotter) and vector displays.

If you wanted a plotter-compatible font for Persian, you'd need to trace the characters you want and convert the traces to "pen down", "move to" and "pen up" instructions.

Hope this helps!

**Comment by mkeyno** [comment]
which software with  "pen down", "move to" and "pen up" instructions  you refer to ?
